version: 2.0
jobs:
  test_feature:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle test
      - store_test_results:
          path: build/test-results
  test_and_build_master:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
  dockerize:
    machine: true
    steps:
     - checkout
     # Login to docker
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t kimhotdk/gildedrose:$CIRCLE_SHA1 .

     # deploy the image
     - run: docker push kimhotdk/gildedrose:$CIRCLE_SHA1

workflows:
  version: 2
  three_job_flow:
    jobs:
      - test_feature
      - test_and_build_master:
          requires:
            - test_feature
      - dockerize:
          requires:
            - test_feature
            - test_and_build_master
